# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "test" ]
    tags: [ "v*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PDF: output.pdf

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: amutake/satysfi:0.0.7-slim
      volumes: 
        - ${{ github.workspace }}:/satysfi

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: build test.pdf
        run: 'satysfi test.saty -o ${{ env.PDF }}'
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ env.PDF }}
          
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: PDF
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          gh release create ${VERSION} -t "${VERSION}" ./${{ env.PDF }}
          
